"""Phase 6: data for the real-vs-forged game and the post's main figure.

Usage:  python pipeline/05_game_data.py
Writes game/game_data.json. The website only reads this file; it never calls a model.
"""
from __future__ import annotations

import importlib
import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import config  # noqa: E402
import textstats as ts  # noqa: E402

load_forgery = importlib.import_module("03_features").load_forgery
SHORT = {"sent_len_mean": "mean sentence length"}


def main() -> None:
    articles = json.loads(config.ARTICLES_FILE.read_text(encoding="utf-8"))
    sample = json.loads(config.SAMPLE_FILE.read_text(encoding="utf-8"))["sample"]
    corpus = ts.RealCorpus(articles, ts.stopwords())
    det = json.loads((config.OUTPUTS_DIR / "detector_D1.json").read_text(encoding="utf-8"))
    pred = pd.read_csv(config.OUTPUTS_DIR / "predictions_D1.csv")
    p = {(r.node_id, r.label): float(r.p_forged_oof) for r in pred.itertuples()}

    pairs = []
    for ch in sample:
        nid = ch["node_id"]
        forged = load_forgery(1, nid)
        if forged is None:
            continue
        real_x, forged_x = ts.excerpt(ch["comparison_text"]), ts.excerpt(forged)
        pr, pf = p[(nid, 0)], p[(nid, 1)]
        pairs.append({
            "id": nid, "name": ch["name"], "tier": ch["tier"], "in_degree": ch["in_degree"],
            "url": articles[nid]["url"],
            "real": real_x, "forged": ts.segments_unseen(corpus, forged_x, nid),
            "real_words": len(ts.tokens(real_x)), "forged_words": len(ts.tokens(forged_x)),
            "p_real_doc": round(pr, 3), "p_forged_doc": round(pf, 3), "detector_correct": pf > pr,
        })

    single = det["single_feature"]
    best = max(single, key=lambda f: single[f]["pair_accuracy"])
    data = {
        "about": ("Real text: Wikipedia, CC BY-SA 4.0. Forged text: AI-generated by Claude Fable 5.1 subagents. "
                  "Detector probabilities are out-of-fold: each pair was scored by a D1 model that never saw "
                  "that character."),
        "rounds": {"1": {"available": True, "pairs": pairs},
                   "2": {"available": False, "note": "not run"}, "3": {"available": False, "note": "not run"}},
        "figure": {
            "metric": "pair accuracy: share of characters where the forgery is the one picked as forged",
            "bars": [
                {"label": "Coin flip", "value": 0.5, "kind": "reference"},
                {"label": f"Best single feature: {SHORT.get(best, best)}", "value": single[best]["pair_accuracy"],
                 "kind": "detector"},
                {"label": "Detector D1 (all 12 features)", "value": det["cv"]["pair_accuracy"], "kind": "detector"},
                {"label": "Humans (classmates, from the game)", "value": None, "kind": "human"},
            ],
            "d1": det["cv"],
        },
    }
    # Headline numbers and the real-vs-AI "tells" for the presentation page
    feat = pd.read_csv(config.OUTPUTS_DIR / "features.csv")
    r1 = feat[feat["round"].isin([0, 1])]
    med = r1.groupby("label")[ts.FEATURES].median()
    data["tells"] = [{"feature": f, "real": float(med.loc[0, f]), "forged": float(med.loc[1, f]),
                      "pair_accuracy": single[f]["pair_accuracy"]}
                     for f in ("sent_len_mean", "dash_rate", "paren_rate", "unseen_bigram_rate")]
    data["stats"] = {"n_pairs": len(pairs), "n_features": len(ts.FEATURES),
                     "d1_pair_accuracy": det["cv"]["pair_accuracy"],
                     "d1_pairs_right": int(sum(x["detector_correct"] for x in pairs)),
                     "best_single_feature": best, "best_single_pair_accuracy": single[best]["pair_accuracy"]}
    check = json.loads((config.FORGERIES_DIR / "round1" / "check.json").read_text(encoding="utf-8"))
    usage = pd.read_csv(config.USAGE_LOG)
    usage = usage[usage["label"] == "round1"]
    data["stats"].update({"forged_words": int(sum(v.get("clean_words", 0) for v in check.values())),
                          "forger_minutes": int(round(usage["duration_s"].sum() / 60)),
                          "forger_model": "Claude Fable 5.1"})
    out = config.GAME_DIR / "game_data.json"
    out.write_text(json.dumps(data, ensure_ascii=False, indent=1), encoding="utf-8")
    wc = [(x["real_words"], x["forged_words"]) for x in pairs]
    print(f"wrote {out.relative_to(config.WEEK5_DIR)}: {len(pairs)} pairs, "
          f"{out.stat().st_size / 1024:.0f} KB; excerpt tokens real {min(a for a, _ in wc)}-{max(a for a, _ in wc)}, "
          f"forged {min(b for _, b in wc)}-{max(b for _, b in wc)}; detector right on "
          f"{sum(x['detector_correct'] for x in pairs)} of {len(pairs)} pairs")


if __name__ == "__main__":
    main()
